### ISSUE TITLE
Creating comment using the SDK do not support `ReplyTo`

### ISSUE THREAD

**Issue by giladt** [anudit/convosdk#4]
## Current Behavior

`comments.create` accepts the following parameters:
```
signerAddress: string, 
token: string, 
comment: string, 
threadId: string, 
url: string, 
metadata?: Dictionary<any>
```

## Expected Behavior

Should accept a `replyTo: string` parameter with a valid `comment _id` value to set that comment as a reply.

## Environment

- Version: "^0.3.17"
- Platform: MacOS
- Node.js Version: "v14.17.3"

**Comment by anudit** [comment]
Added in `v0.3.18`

**Comment by giladt** [comment]
Please note: ReplyTo should be a <string> not a boolean.

```js
create: (
  signerAddress: string, 
  token: string, 
  comment: string, 
  threadId: string, 
  url: string, 
  metadata?: Dictionary<any>, 
  replyTo?: boolean | undefined,  // <== Should be a <string>
  tag1?: string | undefined, 
  tag2?: string | undefined
) => Promise<any | ErrorType>;
```

**Comment by anudit** [comment]
Updated in `v0.3.20`, Thanks @giladt
