### ISSUE TITLE
Error response when SDK performs update: A user can only edit their own comment

### ISSUE THREAD

**Issue by friendlysxw** [anudit/convosdk#6]
## Current Behavior

I signed, verified and generated jwt, I can create comments normally, but I can't update and delete comments, and they report similar errors (A user can only edit/delete their own comment)

## Expected Behavior

I compared the commentId, signerAddress, token in the network request, I don't seem to pass it wrong, it should be successful, maybe I'm missing something? o(╥﹏╥)o

## Steps to Reproduce the Problem

![image](https://user-images.githubusercontent.com/39647464/170712531-85ad25f6-1e67-482e-a87a-39d28ca9ccb1.png)

## Environment

- "@theconvospace/sdk": "^0.4.15",
- Platform: Win
- Node.js Version: v16.13.1

**Comment by anudit** [comment]
Heyo @friendlysxw 👋 Just tried `convo.comments.update` & `convo.comments.delete` all seem to work well. Do have a Code snippet/demo where I can reproduce this? Thanks!

**Comment by friendlysxw** [comment]
Due to the company's business reasons, I have suspended the research on this sdk. This library is very good. I want to take a look at it when I am free. I will close this issue for now
